### ISSUE TITLE
0.4.0?

### ISSUE THREAD

**Issue by kelveden** [alexanderjamesking/clj-wiremock#1]
There are a few improvements in master that haven't yet been propagated to a release to clojars - is there one in the works?

**Comment by alexanderjamesking** [comment]
@kelveden Apologies. I haven't been keeping up to date with this, I decided there was so little code to it that people may as well just use WireMock directly. In hindsight I'd probably just set up a small ring/compojure server for the duration of my tests in order to avoid the dependency on the apache http client.

**Comment by alexanderjamesking** [comment]
ps. you can see an example of using it directly here: https://gist.github.com/alexanderjamesking/a293d5a220d49366afd10fbfde3b2522

**Comment by kelveden** [comment]
Yes, the breadth of the native JSON API is pretty straightforward to use although being able to manage the lifetime of the wiremock server from clojure is still helpful I think.

I can't actually recall what improvement I had been waiting for. In the end I worked around whatever the problem was with a little macro magic something like: https://gist.github.com/kelveden/d4cb8e7ca7cbc0c1b6484ac5dcf35172
